name: flutter_uae_pass
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  fl_chart: ^0.50.1
  path_provider: ^2.0.9
  dio: ^4.0.6
  get_storage: ^2.0.3
  permission_handler: ^9.2.0
  device_info:
  open_file: ^3.2.1
  android_path_provider:
  firebase_core:
  connectivity_plus: ^2.2.1
  checkdigit: ^0.3.1
  pinput: ^1.2.2
  webview_flutter: ^3.0.2
  shimmer: ^2.0.0
  maps_launcher: ^2.0.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  flutter_offline: ^2.1.0
  flutter: 
    sdk: flutter
  device_preview: ^1.0.0
  sizer: ^2.0.15
  firebase_crashlytics: ^2.6.3
  lottie: ^1.3.0
  firebase_analytics: ^9.1.6
  flutter_staggered_animations: ^1.0.0
  flutter_native_splash: ^2.2.0+1
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.5.3+2

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  # uaepass:
  #   path: ./UaePass
  uaepass_plugin:
    path: ./uaepass_plugin
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/robot.png"


flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/drawer-icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/robot.png